INSERT INTO TD_TRABAJADOR (PUESTO, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO) VALUES ('DEV', 'JORGE', 'REYES', 'LOPEZ');
INSERT INTO TD_TRABAJADOR (PUESTO, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO) VALUES ('OPERATIVO', 'DANIEL', 'GALLARDO', 'VELAZQUEZ');
INSERT INTO TD_TRABAJADOR (PUESTO, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO) VALUES ('OPERATIVO', 'LUIS', 'TRUJILLO', 'GALVEZ');
