#ws-trabajador
ws.trabajador.host=${WS_TRABAJADOR:http://localhost:8080}
ws.trabajador.path=/checador
ws.trabajador.checador.reporteAsistencia=/reporteAsistencia

#OPENSHIFT
openshift.volumen.persistente=${RUTA_VOLUMEN:D:\\Desarrollo\\GitHub\\Microservicios}