spring.application.name=ws-nomina
server.port=8081

#Configuración Extra varaibles de entorino api.properties
spring.config.import=classpath:api.properties

#Swagger configurations
springdoc.api-docs.enabled=true

# Spring Data JPA configuration
# H2 in-memory database configuration
# jdbc:h2: → Driver JDBC de H2. 
# mem: → Especifica que la BD está en memoria (no se guarda en disco).
# db → Nombre de la base de datos.
spring.datasource.url=jdbc:h2:mem:db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=meme
spring.datasource.password=
# Habilita la visualización WEB localhost:8080/h2-console/ El puerto puede variar
spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# none → (Default) No realiza ninguna acción sobre el esquema.
# validate → Verifica que el esquema coincida con las entidades. Si no, lanza error.
# update → Ajusta el esquema automáticamente (agrega columnas/tablas si es necesario).
# create → Crea el esquema desde cero en cada inicio (elimina datos previos).
# create-drop → Igual que create, pero elimina el esquema al cerrar la app
spring.jpa.hibernate.ddl-auto=update